### ISSUE TITLE
Needs namespace to prevent namespace conflicts

### ISSUE THREAD

**Issue by snarlynarwhal** [forestrf/UnityAnimatorEvents#4]
Just brought the scripts into my project and get a ton of compiler errors.

**Comment by forestrf** [comment]
I'm quite busy, so even if it is a simple and needed change, I'm not sure I will be able to do it soon. I expect I will be able to do it this weekend given how simple the change is.

**Comment by snarlynarwhal** [comment]
Okay, awesome! Yeah I just added a namespace for now, but figured it'd be better for you to add it to the repository so that I don't need to re-add the namespaces if I need to update the scripts in the future for whatever reason. Thanks!

If you end up not having time, I can make a PR - just let me know what namespace you'd like to use.

**Comment by forestrf** [comment]
I just fixed it in f81083ff226bf2c106d8ee5f37eb8e140e60981e
